" .vimrc recommended by SFIM (but mostly Josh)
" Heavily sourced from: https://vim.fandom.com/wiki/Example_vimrc
" Thanks vim fandom!!
"
" Determine filetype from name, contents; set sensible auto-indenting
filetype indent plugin on 

" Ward off the unexpected per above link
set nocompatible

" Automatically indent if no file-specific indent
set autoindent

" Syntax highlighting; just do it
syntax on

" Set search casing
set ignorecase
" Switch to case-sensitive if capital letters are present
set smartcase

" Allow backspacing over autoindent, line breaks, and start of insert
set backspace=indent,eol,start

" Prevent some moves from going to first character in line
set nostartofline

" Ask if you want to save when quitting without write
set confirm

" Use visual bell instead of beeping
set visualbell

" Uncomment to allow mouse use
" Josh T does not recommend this. Embrace the keyboard.
"set mouse=a

" Display line numbers
set number

" Use <F11> to toggle between paste/no paste
set pastetoggle=<F11>

" Tabs and spaces are contentious.
" To match the field, the defaults are set as spaces by default, Josh
" disagrees with this.
set shiftwidth=4
set softtabstop=4
set expandtab

" Josh T likes 8 spaces and real tabs on C code
autocmd Filetype c setlocal sw=8 ts=8 noexpandtab

" Wrap text at 75 characters, assumes 80-character width while giving
" breathing room for files with 5-digit line numbers.
set textwidth=75

" Jump back to last edit on file before closing
" Thanks to: https://askubuntu.com/questions/202075/how-do-i-get-vim-to-remember-the-line-i-was-on-when-i-reopen-a-file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif

" Highlight search
" See mappings: custom keybind <C-L> redraws with no highlight until next
" search
set hlsearch

"--------
"MAPPINGS
"--------

" Map [Ctrl]-L to turn off search highlighting until next search 
" and redraw screen
nnoremap <C-L> : nohl<CR><C-L>
